/**
 * @File Name          : newApexClass.cls
 * @Description        : 
 * @Author             : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Group              : 
 * @Last Modified By   : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Last Modified On   : 2/14/2020, 1:48:44 PM
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    2/13/2020   ChangeMeIn@UserSettingsUnder.SFDoc     Initial Version
**/
public with sharing class NewApexClass {
    public newApexClass() {
        system.debug('Test');
    }
}